In [1]:
import pandas as pd
import numpy as np
df=pd.read_csv("../data/dataset.csv")
df.head()

,PatientId,AppointmentID,Gender,ScheduledDay,AppointmentDay,Age,Neighbourhood,Scholarship,Hipertension,Diabetes,Alcoholism,Handcap,SMS_received,No-show
0,2.987250e+13,5642903,F,2016-04-29T18:38:08Z,2016-04-29T00:00:00Z,62,JARDIM DA PENHA,0,1,0,0,0,0,No
1,5.589978e+14,5642503,M,2016-04-29T16:08:27Z,2016-04-29T00:00:00Z,56,JARDIM DA PENHA,0,0,0,0,0,0,No
2,4.262962e+12,5642549,F,2016-04-29T16:19:04Z,2016-04-29T00:00:00Z,62,MATA DA PRAIA,0,0,0,0,0,0,No
3,8.679512e+11,5642828,F,2016-04-29T17:29:31Z,2016-04-29T00:00:00Z,8,PONTAL DE CAMBURI,0,0,0,0,0,0,No
4,8.841186e+12,5642494,F,2016-04-29T16:07:23Z,2016-04-29T00:00:00Z,56,JARDIM DA PENHA,0,1,1,0,0,0,No

In [2]:
df.columns

Index(['PatientId', 'AppointmentID', 'Gender', 'ScheduledDay',
       'AppointmentDay', 'Age', 'Neighbourhood', 'Scholarship', 'Hipertension',
       'Diabetes', 'Alcoholism', 'Handcap', 'SMS_received', 'No-show'],
      dtype='str')

In [3]:
df.rename(columns={
    'PatientId': 'patient_id',
    'AppointmentID': 'appointment_id',
    'Gender': 'gender',
    'ScheduledDay': 'scheduled_day',
    'AppointmentDay': 'appointment_day',
    'Age': 'age',
    'Neighbourhood': 'neighbourhood',
    'Scholarship': 'scholarship',
    'Hipertension': 'hypertension',
    'Diabetes': 'diabetes',
    'Alcoholism': 'alcoholism',
    'Handcap': 'handicap',
    'SMS_received': 'sms_received',
    'No-show': 'no_show'
}, inplace=True)

In [4]:
df.columns

Index(['patient_id', 'appointment_id', 'gender', 'scheduled_day',
       'appointment_day', 'age', 'neighbourhood', 'scholarship',
       'hypertension', 'diabetes', 'alcoholism', 'handicap', 'sms_received',
       'no_show'],
      dtype='str')

In [6]:
df.dtypes

patient_id         float64
appointment_id       int64
gender                 str
scheduled_day          str
appointment_day        str
age                  int64
neighbourhood          str
scholarship          int64
hypertension         int64
diabetes             int64
alcoholism           int64
handicap             int64
sms_received         int64
no_show                str
dtype: object

In [7]:
df['scheduled_day'] = pd.to_datetime(df['scheduled_day'])
df['appointment_day'] = pd.to_datetime(df['appointment_day'])

In [8]:
df.dtypes

patient_id                     float64
appointment_id                   int64
gender                             str
scheduled_day      datetime64[us, UTC]
appointment_day    datetime64[us, UTC]
age                              int64
neighbourhood                      str
scholarship                      int64
hypertension                     int64
diabetes                         int64
alcoholism                       int64
handicap                         int64
sms_received                     int64
no_show                            str
dtype: object

In [9]:
df['age'].describe()

count    110527.000000
mean         37.088874
std          23.110205
min          -1.000000
25%          18.000000
50%          37.000000
75%          55.000000
max         115.000000
Name: age, dtype: float64

In [12]:
df.isnull().sum()

patient_id         0
appointment_id     0
gender             0
scheduled_day      0
appointment_day    0
age                0
neighbourhood      0
scholarship        0
hypertension       0
diabetes           0
alcoholism         0
handicap           0
sms_received       0
no_show            0
dtype: int64

In [13]:
df.duplicated().sum()

np.int64(0)

In [14]:
df['no_show'].value_counts()

no_show
No     88208
Yes    22319
Name: count, dtype: int64

In [15]:
df['no_show'] = df['no_show'].map({
    'No': 0,
    'Yes': 1
})

In [16]:
df['no_show'].value_counts()

no_show
0    88208
1    22319
Name: count, dtype: int64

In [17]:
df['waiting_days'] = (df['appointment_day'] - df['scheduled_day']).dt.days

In [18]:
df[['scheduled_day', 'appointment_day', 'waiting_days']].head()

              scheduled_day           appointment_day  waiting_days
0 2016-04-29 18:38:08+00:00 2016-04-29 00:00:00+00:00            -1
1 2016-04-29 16:08:27+00:00 2016-04-29 00:00:00+00:00            -1
2 2016-04-29 16:19:04+00:00 2016-04-29 00:00:00+00:00            -1
3 2016-04-29 17:29:31+00:00 2016-04-29 00:00:00+00:00            -1
4 2016-04-29 16:07:23+00:00 2016-04-29 00:00:00+00:00            -1

In [19]:
df['appointment_weekday'] = df['appointment_day'].dt.day_name()

In [20]:
df[['appointment_day', 'appointment_weekday']].head()

            appointment_day appointment_weekday
0 2016-04-29 00:00:00+00:00              Friday
1 2016-04-29 00:00:00+00:00              Friday
2 2016-04-29 00:00:00+00:00              Friday
3 2016-04-29 00:00:00+00:00              Friday
4 2016-04-29 00:00:00+00:00              Friday

In [21]:
df['scheduled_hour'] = df['scheduled_day'].dt.hour
df[['scheduled_day', 'scheduled_hour']].head()

              scheduled_day  scheduled_hour
0 2016-04-29 18:38:08+00:00              18
1 2016-04-29 16:08:27+00:00              16
2 2016-04-29 16:19:04+00:00              16
3 2016-04-29 17:29:31+00:00              17
4 2016-04-29 16:07:23+00:00              16

In [22]:
df[df['waiting_days'] < 0][['scheduled_day', 'appointment_day', 'waiting_days']].head()

              scheduled_day           appointment_day  waiting_days
0 2016-04-29 18:38:08+00:00 2016-04-29 00:00:00+00:00            -1
1 2016-04-29 16:08:27+00:00 2016-04-29 00:00:00+00:00            -1
2 2016-04-29 16:19:04+00:00 2016-04-29 00:00:00+00:00            -1
3 2016-04-29 17:29:31+00:00 2016-04-29 00:00:00+00:00            -1
4 2016-04-29 16:07:23+00:00 2016-04-29 00:00:00+00:00            -1

In [23]:
(df['waiting_days'] < 0).sum()

np.int64(38568)

In [24]:
df[df['waiting_days'] < 0][['scheduled_day', 'appointment_day', 'waiting_days']].head(10)

               scheduled_day           appointment_day  waiting_days
0  2016-04-29 18:38:08+00:00 2016-04-29 00:00:00+00:00            -1
1  2016-04-29 16:08:27+00:00 2016-04-29 00:00:00+00:00            -1
2  2016-04-29 16:19:04+00:00 2016-04-29 00:00:00+00:00            -1
3  2016-04-29 17:29:31+00:00 2016-04-29 00:00:00+00:00            -1
4  2016-04-29 16:07:23+00:00 2016-04-29 00:00:00+00:00            -1
8  2016-04-29 08:02:16+00:00 2016-04-29 00:00:00+00:00            -1
19 2016-04-29 10:43:14+00:00 2016-04-29 00:00:00+00:00            -1
24 2016-04-29 14:19:19+00:00 2016-04-29 00:00:00+00:00            -1
26 2016-04-29 14:19:42+00:00 2016-04-29 00:00:00+00:00            -1
28 2016-04-29 15:48:02+00:00 2016-04-29 00:00:00+00:00            -1

In [25]:
df['scheduled_day'].min(), df['scheduled_day'].max()

(Timestamp('2015-11-10 07:13:56+0000', tz='UTC'),
 Timestamp('2016-06-08 20:07:23+0000', tz='UTC'))

In [26]:
df['appointment_day'].min(), df['appointment_day'].max()

(Timestamp('2016-04-29 00:00:00+0000', tz='UTC'),
 Timestamp('2016-06-08 00:00:00+0000', tz='UTC'))

In [27]:
df['scheduled_day'] = df['scheduled_day'].dt.normalize()

df['waiting_days'] = (df['appointment_day'] - df['scheduled_day']).dt.days

In [28]:
df['waiting_days'].describe()

count    110527.000000
mean         10.183702
std          15.254996
min          -6.000000
25%           0.000000
50%           4.000000
75%          15.000000
max         179.000000
Name: waiting_days, dtype: float64

In [29]:
(df['waiting_days'] < 0).sum()

np.int64(5)

In [30]:
df[df['waiting_days'] < 0][['scheduled_day', 'appointment_day', 'waiting_days']]

                  scheduled_day           appointment_day  waiting_days
27033 2016-05-10 00:00:00+00:00 2016-05-09 00:00:00+00:00            -1
55226 2016-05-18 00:00:00+00:00 2016-05-17 00:00:00+00:00            -1
64175 2016-05-05 00:00:00+00:00 2016-05-04 00:00:00+00:00            -1
71533 2016-05-11 00:00:00+00:00 2016-05-05 00:00:00+00:00            -6
72362 2016-05-04 00:00:00+00:00 2016-05-03 00:00:00+00:00            -1

In [31]:
df = df[df['waiting_days'] >= 0]

In [32]:
(df['waiting_days'] < 0).sum()

np.int64(0)

In [34]:
df.shape

(110522, 17)

In [35]:
df.drop(columns=[
    'patient_id',
    'appointment_id',
    'scheduled_day',
    'appointment_day'
], inplace=True)

In [37]:

df.head()

,gender,age,neighbourhood,scholarship,hypertension,diabetes,alcoholism,handicap,sms_received,no_show,waiting_days,appointment_weekday,scheduled_hour
0,F,62,JARDIM DA PENHA,0,1,0,0,0,0,0,0,Friday,18
1,M,56,JARDIM DA PENHA,0,0,0,0,0,0,0,0,Friday,16
2,F,62,MATA DA PRAIA,0,0,0,0,0,0,0,0,Friday,16
3,F,8,PONTAL DE CAMBURI,0,0,0,0,0,0,0,0,Friday,17
4,F,56,JARDIM DA PENHA,0,1,1,0,0,0,0,0,Friday,16

In [39]:
df.select_dtypes(include=['object', 'str']).columns

Index(['gender', 'neighbourhood', 'appointment_weekday'], dtype='str')

In [40]:
df['gender'].unique()

<StringArray>
['F', 'M']
Length: 2, dtype: str

In [41]:
df['appointment_weekday'].unique()

<StringArray>
['Friday', 'Tuesday', 'Monday', 'Wednesday', 'Thursday', 'Saturday']
Length: 6, dtype: str

In [42]:
df['neighbourhood'].nunique()

81

In [43]:
df['gender'] = df['gender'].map({
    'M': 1,
    'F': 0
})

In [44]:
df['gender'].value_counts()

gender
0    71837
1    38685
Name: count, dtype: int64

In [45]:
df = pd.get_dummies(df, columns=['appointment_weekday'], drop_first=True)

In [46]:
df.head()

,gender,age,neighbourhood,scholarship,hypertension,diabetes,alcoholism,handicap,sms_received,no_show,waiting_days,scheduled_hour,appointment_weekday_Monday,appointment_weekday_Saturday,appointment_weekday_Thursday,appointment_weekday_Tuesday,appointment_weekday_Wednesday
0,0,62,JARDIM DA PENHA,0,1,0,0,0,0,0,0,18,False,False,False,False,False
1,1,56,JARDIM DA PENHA,0,0,0,0,0,0,0,0,16,False,False,False,False,False
2,0,62,MATA DA PRAIA,0,0,0,0,0,0,0,0,16,False,False,False,False,False
3,0,8,PONTAL DE CAMBURI,0,0,0,0,0,0,0,0,17,False,False,False,False,False
4,0,56,JARDIM DA PENHA,0,1,1,0,0,0,0,0,16,False,False,False,False,False

In [47]:
df.shape

(110522, 17)

In [48]:
df = pd.get_dummies(df, columns=['neighbourhood'], drop_first=True)

In [49]:
df.shape

(110522, 96)

In [50]:
df.head()

,gender,age,scholarship,hypertension,diabetes,alcoholism,handicap,sms_received,no_show,waiting_days,...,neighbourhood_SANTOS REIS,neighbourhood_SEGURANÇA DO LAR,neighbourhood_SOLON BORGES,neighbourhood_SÃO BENEDITO,neighbourhood_SÃO CRISTÓVÃO,neighbourhood_SÃO JOSÉ,neighbourhood_SÃO PEDRO,neighbourhood_TABUAZEIRO,neighbourhood_UNIVERSITÁRIO,neighbourhood_VILA RUBIM
0,0,62,0,1,0,0,0,0,0,0,...,False,False,False,False,False,False,False,False,False,False
1,1,56,0,0,0,0,0,0,0,0,...,False,False,False,False,False,False,False,False,False,False
2,0,62,0,0,0,0,0,0,0,0,...,False,False,False,False,False,False,False,False,False,False
3,0,8,0,0,0,0,0,0,0,0,...,False,False,False,False,False,False,False,False,False,False
4,0,56,0,1,1,0,0,0,0,0,...,False,False,False,False,False,False,False,False,False,False

In [51]:
df.dtypes

gender                         int64
age                            int64
scholarship                    int64
hypertension                   int64
diabetes                       int64
                               ...
neighbourhood_SÃO JOSÉ          bool
neighbourhood_SÃO PEDRO         bool
neighbourhood_TABUAZEIRO        bool
neighbourhood_UNIVERSITÁRIO     bool
neighbourhood_VILA RUBIM        bool
Length: 96, dtype: object

In [52]:
df.isnull().sum().sum()

np.int64(0)

In [53]:
df.head()

,gender,age,scholarship,hypertension,diabetes,alcoholism,handicap,sms_received,no_show,waiting_days,...,neighbourhood_SANTOS REIS,neighbourhood_SEGURANÇA DO LAR,neighbourhood_SOLON BORGES,neighbourhood_SÃO BENEDITO,neighbourhood_SÃO CRISTÓVÃO,neighbourhood_SÃO JOSÉ,neighbourhood_SÃO PEDRO,neighbourhood_TABUAZEIRO,neighbourhood_UNIVERSITÁRIO,neighbourhood_VILA RUBIM
0,0,62,0,1,0,0,0,0,0,0,...,False,False,False,False,False,False,False,False,False,False
1,1,56,0,0,0,0,0,0,0,0,...,False,False,False,False,False,False,False,False,False,False
2,0,62,0,0,0,0,0,0,0,0,...,False,False,False,False,False,False,False,False,False,False
3,0,8,0,0,0,0,0,0,0,0,...,False,False,False,False,False,False,False,False,False,False
4,0,56,0,1,1,0,0,0,0,0,...,False,False,False,False,False,False,False,False,False,False

In [54]:
df = df.astype(int)

In [55]:
df.dtypes

gender                         int64
age                            int64
scholarship                    int64
hypertension                   int64
diabetes                       int64
                               ...
neighbourhood_SÃO JOSÉ         int64
neighbourhood_SÃO PEDRO        int64
neighbourhood_TABUAZEIRO       int64
neighbourhood_UNIVERSITÁRIO    int64
neighbourhood_VILA RUBIM       int64
Length: 96, dtype: object

In [56]:
df.info()

<class 'pandas.DataFrame'>
Index: 110522 entries, 0 to 110526
Data columns (total 96 columns):
 #   Column                                     Non-Null Count   Dtype
---  ------                                     --------------   -----
 0   gender                                     110522 non-null  int64
 1   age                                        110522 non-null  int64
 2   scholarship                                110522 non-null  int64
 3   hypertension                               110522 non-null  int64
 4   diabetes                                   110522 non-null  int64
 5   alcoholism                                 110522 non-null  int64
 6   handicap                                   110522 non-null  int64
 7   sms_received                               110522 non-null  int64
 8   no_show                                    110522 non-null  int64
 9   waiting_days                               110522 non-null  int64
 10  scheduled_hour                             110522 non-null  int64
 11  appointment_weekday_Monday                 110522 non-null  int64
 12  appointment_weekday_Saturday               110522 non-null  int64
 13  appointment_weekday_Thursday               110522 non-null  int64
 14  appointment_weekday_Tuesday                110522 non-null  int64
 15  appointment_weekday_Wednesday              110522 non-null  int64
 16  neighbourhood_ANDORINHAS                   110522 non-null  int64
 17  neighbourhood_ANTÔNIO HONÓRIO              110522 non-null  int64
 18  neighbourhood_ARIOVALDO FAVALESSA          110522 non-null  int64
 19  neighbourhood_BARRO VERMELHO               110522 non-null  int64
 20  neighbourhood_BELA VISTA                   110522 non-null  int64
 21  neighbourhood_BENTO FERREIRA               110522 non-null  int64
 22  neighbourhood_BOA VISTA                    110522 non-null  int64
 23  neighbourhood_BONFIM                       110522 non-null  int64
 24  neighbourhood_CARATOÍRA                    110522 non-null  int64
 25  neighbourhood_CENTRO                       110522 non-null  int64
 26  neighbourhood_COMDUSA                      110522 non-null  int64
 27  neighbourhood_CONQUISTA                    110522 non-null  int64
 28  neighbourhood_CONSOLAÇÃO                   110522 non-null  int64
 29  neighbourhood_CRUZAMENTO                   110522 non-null  int64
 30  neighbourhood_DA PENHA                     110522 non-null  int64
 31  neighbourhood_DE LOURDES                   110522 non-null  int64
 32  neighbourhood_DO CABRAL                    110522 non-null  int64
 33  neighbourhood_DO MOSCOSO                   110522 non-null  int64
 34  neighbourhood_DO QUADRO                    110522 non-null  int64
 35  neighbourhood_ENSEADA DO SUÁ               110522 non-null  int64
 36  neighbourhood_ESTRELINHA                   110522 non-null  int64
 37  neighbourhood_FONTE GRANDE                 110522 non-null  int64
 38  neighbourhood_FORTE SÃO JOÃO               110522 non-null  int64
 39  neighbourhood_FRADINHOS                    110522 non-null  int64
 40  neighbourhood_GOIABEIRAS                   110522 non-null  int64
 41  neighbourhood_GRANDE VITÓRIA               110522 non-null  int64
 42  neighbourhood_GURIGICA                     110522 non-null  int64
 43  neighbourhood_HORTO                        110522 non-null  int64
 44  neighbourhood_ILHA DAS CAIEIRAS            110522 non-null  int64
 45  neighbourhood_ILHA DE SANTA MARIA          110522 non-null  int64
 46  neighbourhood_ILHA DO BOI                  110522 non-null  int64
 47  neighbourhood_ILHA DO FRADE                110522 non-null  int64
 48  neighbourhood_ILHA DO PRÍNCIPE             110522 non-null  int64
 49  neighbourhood_ILHAS OCEÂNICAS DE TRINDADE  110522 non-null  int64
 50  neighbourhood_INHANGUETÁ                   110522 non-null  int64
 51  neighbourhood_ITARARÉ                      110522 non-null  int64
 52  neighbourhood_JABOUR                       110522 non-null  int64
 53  neighbourhood_JARDIM CAMBURI               110522 non-null  int64
 54  neighbourhood_JARDIM DA PENHA              110522 non-null  int64
 55  neighbourhood_JESUS DE NAZARETH            110522 non-null  int64
 56  neighbourhood_JOANA D´ARC                  110522 non-null  int64
 57  neighbourhood_JUCUTUQUARA                  110522 non-null  int64
 58  neighbourhood_MARIA ORTIZ                  110522 non-null  int64
 59  neighbourhood_MARUÍPE                      110522 non-null  int64
 60  neighbourhood_MATA DA PRAIA                110522 non-null  int64
 61  neighbourhood_MONTE BELO                   110522 non-null  int64
 62  neighbourhood_MORADA DE CAMBURI            110522 non-null  int64
 63  neighbourhood_MÁRIO CYPRESTE               110522 non-null  int64
 64  neighbourhood_NAZARETH                     110522 non-null  int64
 65  neighbourhood_NOVA PALESTINA               110522 non-null  int64
 66  neighbourhood_PARQUE INDUSTRIAL            110522 non-null  int64
 67  neighbourhood_PARQUE MOSCOSO               110522 non-null  int64
 68  neighbourhood_PIEDADE                      110522 non-null  int64
 69  neighbourhood_PONTAL DE CAMBURI            110522 non-null  int64
 70  neighbourhood_PRAIA DO CANTO               110522 non-null  int64
 71  neighbourhood_PRAIA DO SUÁ                 110522 non-null  int64
 72  neighbourhood_REDENÇÃO                     110522 non-null  int64
 73  neighbourhood_REPÚBLICA                    110522 non-null  int64
 74  neighbourhood_RESISTÊNCIA                  110522 non-null  int64
 75  neighbourhood_ROMÃO                        110522 non-null  int64
 76  neighbourhood_SANTA CECÍLIA                110522 non-null  int64
 77  neighbourhood_SANTA CLARA                  110522 non-null  int64
 78  neighbourhood_SANTA HELENA                 110522 non-null  int64
 79  neighbourhood_SANTA LUÍZA                  110522 non-null  int64
 80  neighbourhood_SANTA LÚCIA                  110522 non-null  int64
 81  neighbourhood_SANTA MARTHA                 110522 non-null  int64
 82  neighbourhood_SANTA TEREZA                 110522 non-null  int64
 83  neighbourhood_SANTO ANDRÉ                  110522 non-null  int64
 84  neighbourhood_SANTO ANTÔNIO                110522 non-null  int64
 85  neighbourhood_SANTOS DUMONT                110522 non-null  int64
 86  neighbourhood_SANTOS REIS                  110522 non-null  int64
 87  neighbourhood_SEGURANÇA DO LAR             110522 non-null  int64
 88  neighbourhood_SOLON BORGES                 110522 non-null  int64
 89  neighbourhood_SÃO BENEDITO                 110522 non-null  int64
 90  neighbourhood_SÃO CRISTÓVÃO                110522 non-null  int64
 91  neighbourhood_SÃO JOSÉ                     110522 non-null  int64
 92  neighbourhood_SÃO PEDRO                    110522 non-null  int64
 93  neighbourhood_TABUAZEIRO                   110522 non-null  int64
 94  neighbourhood_UNIVERSITÁRIO                110522 non-null  int64
 95  neighbourhood_VILA RUBIM                   110522 non-null  int64
dtypes: int64(96)
memory usage: 81.8 MB

In [57]:
df.isnull().sum().sum()

np.int64(0)

In [58]:
df['no_show'].value_counts()

no_show
0    88208
1    22314
Name: count, dtype: int64

In [59]:
df.to_csv("../data/processed/cleaned_medical_appointments.csv", index=False)

In [60]:
import os
os.listdir("../data/processed")

['.ipynb_checkpoints', 'cleaned_medical_appointments.csv']